<?xml version="1.0" encoding="utf-8"?>
<report>
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="17a6cdb0fb293dfa"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		user="automation"
		host="DESKTOP-IP0304R"
		rxversion="5.4.0.24580"
		osversion="Windows 10 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		language="en-US"
		screenresolution="1024x768"
		timestamp="2/14/2016 2:55:23 PM"
		timestampiso="2016-02-14T19:55:23"
		timeoutfactor="1"
		module="LoginModule">
		<detail>
			LoginModule
		</detail>
		<varbindings/>
		<item
			timeRelativeToTestSuiteStartTime="01:24.093"
			timeRelativeToTestModuleStartTime="01:24.093"
			timeWallClock="14:56:48"
			time="01:24.093"
			level="Error"
			category="Module">
			<message>
				Test run was aborted by the user.
			</message>
			<metainfo
				loglvl="Error"/>
		</item>
	</activity>
</report>
